### ISSUE TITLE
Enum cases are reported as undefined constants

### ISSUE THREAD

**Issue by mabar** [mesour-intellij-plugins/latte-pro-issues#10]
** Environment:
- PhpStorm version [e.g. 2022.2]
- Plugin version [e.g. 1.0.1]

![image](https://user-images.githubusercontent.com/20974277/183979893-7a3a4eb2-a441-4e34-82ad-a151da7d5f6f.png)

```php
namespace App\Invoice\DB;

enum InvoiceState: string
{

	case Draft = 'draft';
	case Ready = 'ready';
	case Paid = 'paid';
	case Unpaid = 'unpaid';

}
```

**Comment by mesour** [comment]
I will add support for enum cases also to completion, references and I will upgrade inspection, it will distinguish enum class from normal class constants.
