### ISSUE TITLE
java.lang.NoSuchFieldException: SPACE_BEFORE_CLOSING_UNPAIRED_TAG

### ISSUE THREAD

**Issue by Rashengka** [mesour-intellij-plugins/latte-pro-issues#102]
On PHPStorm start error pops up
[backtrace_1.txt](https://github.com/mesour-intellij-plugins/latte-pro-issues/files/11198724/backtrace_1.txt)

**Comment by mesour** [comment]
Is the problem still persist? If yes, I will need some example code or describe some steps, how to reproduce it.

**Comment by Rashengka** [comment]
@mesour problem has disappeared, possibly after phpstorm new version release

**Comment by mesour** [comment]
Super, I'm closing issue
