### ISSUE TITLE
File inspection vs. Code inspection

### ISSUE THREAD

**Issue by martinbohmcz** [mesour-intellij-plugins/latte-pro-issues#11]
**Describe the bug**
Inspections in top right corner of the screen shows errors, but when I run "Code / Inspect code" **on the whole project**, those errors are not reported. Even if all inspections are checked.

**Environment (please complete the following information):**
- PhpStorm version [e.g. 2022.2]
- Plugin version [e.g. 1.0.1]

**To Reproduce**
1. Open file containing an error.
2. Check the "top right" inspection
3. Run "Code / Inspect code" from menu **on the whole project**
4. See result

**Screenshots**
![image](https://user-images.githubusercontent.com/15814845/183980521-56dc37de-d8c7-413a-96aa-3ab56507211f.png)

**Comment by mabar** [comment]
@martinbohmcz 
Click on the error to open list
In list double click on the error
Hover above chosen line
Does it show any error? If yes then it's color settings, if not then code sample with reproduction may be helpful

**Comment by mesour** [comment]
@martinbohmcz is it still mismatch in 1.0.4?

**Comment by martinbohmcz** [comment]
I have my own filter, which the plugin does not know. It is being reported in the top right corner as well as in the "Code / Inspect code…" report. So I consider this issue fixed.
