### ISSUE TITLE
Intersection of two iterable types in foreach results into mixed item

### ISSUE THREAD

**Issue by mabar** [mesour-intellij-plugins/latte-pro-issues#12]
** Environment:
- PhpStorm version [e.g. 2022.2]
- Plugin version [e.g. 1.0.1]

Problematic type is `array<File>&HasMany` (originally declared as `iterable<File>&HasMany`)

Union type `array<File>|HasMany` works just fine. Standalone type `array<File>` works too.

It would probably be enough to treat `&` same way as `|`

![image](https://user-images.githubusercontent.com/20974277/183980789-81ab4b7f-81a6-469c-a27b-820da07d3dd4.png)
![image](https://user-images.githubusercontent.com/20974277/183980811-c0934821-3487-4813-9e26-093f5def8372.png)

**Comment by mesour** [comment]
This is probably problem with detection `&` in types
