### ISSUE TITLE
Brutal memory usage + slowing down PhpStorm

### ISSUE THREAD

**Issue by forgie1** [mesour-intellij-plugins/latte-pro-issues#121]
**Bug description**
Until I turned off the Latte Pro plugin, PhpStorm crashed multiple times, trying to allocate several GB of memory (e.g. 11 GB).
It also slowed down the work significantly (even if no crash occurred).

**Environment:**
 - PhpStorm version 2023.2.1
 - Plugin version 1.0.11

**Comment by mesour** [comment]
I need more info about project size, how much latte files is in project etc. I have nothing to catch from your description.

**Comment by forgie1** [comment]
I reinstalled PhpStorm and problem disappeared.
Thank you.
