### ISSUE TITLE
Highlighting of {block #foo} should match {block foo}

### ISSUE THREAD

**Issue by mabar** [mesour-intellij-plugins/latte-pro-issues#15]
These two are the same, should not be highlighted differently

```latte
{block #foo}{/block}
{block foo}{/block}
```
![image](https://user-images.githubusercontent.com/20974277/183985373-1d3f1687-3709-460d-adf5-b58a47f6128e.png)

Only use case for `#` in older Latte versions was double-quoted string with PHP. And it is replaced with keyword `block` in newer versions
```latte
{* Old one *}
{ifset #"col-filter-{$column->name}"}{/ifset}

{* New one *}
{ifset block col-filter-{$column->name}}{/ifset}
```
![image](https://user-images.githubusercontent.com/20974277/183986417-eb264474-ab74-4770-89ce-e929fe0422e5.png)

**Comment by mesour** [comment]
Solution is remove special color for blocks
