### ISSUE TITLE
Auto fix for filter used in invalid context

### ISSUE THREAD

**Issue by mabar** [mesour-intellij-plugins/latte-pro-issues#152]
**Is your feature request related to a problem? Please describe.**

Both Latte (since 2.9) and plugin report that filters can't be used in tag {php}. That's not exactly right, because if wrapped in parentheses, the filter works inside {php} tag. https://fiddle.nette.org/latte/#a7e87189e5

**Describe the solution you'd like**

Offer auto fix by wrapping variable and filter in parentheses.

**Additional context**

![image](https://github.com/mesour-intellij-plugins/latte-pro-issues/assets/20974277/853c5716-432e-499b-80d6-2bb7ca86b8c2)

![image](https://github.com/mesour-intellij-plugins/latte-pro-issues/assets/20974277/ee5cd3ff-1ef4-4049-b83e-d8f78afc4b41)

**Comment by mesour** [comment]
It will be fiexed in 1.3
