### ISSUE TITLE
Bad type detection in foreach for `array` types

### ISSUE THREAD

**Issue by SendiMyrkr** [mesour-intellij-plugins/latte-pro-issues#157]
![Snímek obrazovky 2024-02-23 132845](https://github.com/mesour-intellij-plugins/latte-pro-issues/assets/1462122/90f1d5cd-48cb-471b-a654-f2250ad202f1)

i believe that type of $error variable should be mixed, not array. Actually return type of getOwnErrors is array what is equals to array<mixed> or mixed[]

**Comment by mesour** [comment]
Fixed in 1.2.1
