### ISSUE TITLE
{varType} vs <div> issue

### ISSUE THREAD

**Issue by nufue** [mesour-intellij-plugins/latte-pro-issues#160]
**Describe the bug**
`{varType}` does not seem to be working in combination with `<div>`.

**Environment (please complete the following information):**
- PhpStorm version 2023.3.5
- Plugin version 2.0.0@beta1
- PHPStorm cache invalidated and cleaned

**To Reproduce**
1. Paste code below to a new file.
2. See that `$amd` is hinted as undefined variable, even though it is specified in `{varType}`.
3. Additionally when I replace the `<div class="product-detail">` with `<span>`, PHPStorm recognizes `$amd` as defined and of type `App\Model\Standards\Amendment`.

**Code**
```latte
{varType App\Model\Standards\Amendment $amd}

{block content}
	<div class="product-detail">
		{if $amd->isEligibleForOrder()}
		{/if}
	</div>
{/block}
```

**Screenshots**
![image](https://github.com/mesour-intellij-plugins/latte-pro-issues/assets/8158773/09d417a3-d0ed-4d6e-857f-601ff84d2b46)
![image](https://github.com/mesour-intellij-plugins/latte-pro-issues/assets/8158773/40aba264-c0b8-41a4-b1a3-e5907bc4f56e)

**Comment by mesour** [comment]
This was old 2.0 try, it will be work in new 2.0

**Comment by nufue** [comment]
@mesour This issue still persists in plugin version 1.4.0-beta1, PHPStorm version 2025.1.3 (PS-251.26927.60).

I have prepared a repository with templates to reproduce to problem if necessary - https://github.com/nufue/phpstorm-latte-test/tree/9ada2cbd41ad8025bb54484cf8a60d911173fe35/app/Presentation/Home

**test-vartype.latte**: Variables `$gifts` and `$recipient`, which are declared using `{varType}` are reported as undefined when used inside of `<div>`. Autocomplete does not offer them, nor their properties and methods. When placed inside other HTML elements, they appear as defined and everything works as expected.

<img width="589" height="784" alt="Image" src="https://github.com/user-attachments/assets/8ab0a0f7-1c6e-409f-b0b2-0f1cdd2e0235" />

**test-template.latte**: Variables are declared through `{templateType}`, same behaviour.
