### ISSUE TITLE
Variable with Enum class is not recognized 

### ISSUE THREAD

**Issue by Lumeriol** [mesour-intellij-plugins/latte-pro-issues#163]
**Describe the bug**
If I define a variable with class Enum in Latte, it is evaluated as mixed until I explicitly set its type.

**Environment (please complete the following information):**
 - PhpStorm version [2023.x and newer]
 - Plugin version [1.2 and older]

**To Reproduce**
mixed type
![image](https://github.com/mesour-intellij-plugins/latte-pro-issues/assets/3526195/524f23e4-200d-4e16-910a-8f1b6add1f96)

correct type
![image](https://github.com/mesour-intellij-plugins/latte-pro-issues/assets/3526195/9cafefde-3786-4a31-be2c-2d7a0a7213f5)

**Comment by mesour** [comment]
Correct is `string`, because `::class` contains string, not instance of class. It is fixed in 1.3.0, if not, feel free to reopen issue

<img width="412" alt="image" src="https://github.com/mesour-intellij-plugins/latte-pro-issues/assets/1161897/bf4f2d0e-19ec-4cd1-8b5a-ddaff69edbe3">
