### ISSUE TITLE
Undefined function should be new class, not a function

### ISSUE THREAD

**Issue by mabar** [mesour-intellij-plugins/latte-pro-issues#19]
** Environment:
- PhpStorm version [e.g. 2022.2]
- Plugin version [e.g. 1.0.1]

```latte
{var $a = new stdClass()}
{var $b = new \stdClass()}
```

![image](https://user-images.githubusercontent.com/20974277/183989457-61fde5dd-bafc-4ac1-bed0-7d81d101b41e.png)

**Comment by mesour** [comment]
Classes can not be used without namespace or `\`. This is feature not bug.
