### ISSUE TITLE
Add support for comma as separator for Latte filters

### ISSUE THREAD

**Issue by mesour** [mesour-intellij-plugins/latte-pro-issues#20]
`:` will be deprecated. `,` can be used as separator for Latte filter parameters.

Example:
```
{$foo|bar:123, 'test', 456}
```

Old version:
```
{$foo|bar:123: 'test': 456}
```

- [x] Implement it in parser.
- [x] Add support to parameter completion

**Comment by lulco** [comment]
it also works this way:
```
{$foo|bar, 123, 'test', 456}
```
