### ISSUE TITLE
Filter |noescape should be placed at the very end

### ISSUE THREAD

**Issue by martinbohmcz** [mesour-intellij-plugins/latte-pro-issues#25]
**Is your feature request related to a problem? Please describe.**
Nette raises 'User Deprecation' when Lette filter '|noescape' is not placed at the very end of the filter chain.

**Describe the solution you'd like**
The plugin should warn about this.

**Additional context**
This change has come with [Latte v2.11.1](https://github.com/nette/latte/releases/tag/v2.11.1)

**Comment by martinbohmcz** [comment]
It now marks and warns about the "|noescape", when it is not at the very last place. As discussed I will create new featore request for the "one-click" fix.

**Comment by mesour** [comment]
Fixed in `1.0.4`
