### ISSUE TITLE
Closing tag autocomplete

### ISSUE THREAD

**Issue by martinbohmcz** [mesour-intellij-plugins/latte-pro-issues#26]
**Describe the solution you'd like**
When I have an opening tag in code and start typing the closing one, i would like the plugin to suggest (or autocomplete) it.

```
{first}
…
{/…
```
suggest "first}"

**Comment by mesour** [comment]
Done, I will try show dialog automatically

**Comment by mesour** [comment]
I try show dialog automatically, but it is not working. I will close this issue, it is working with `ctrl+space` in `1.0.4`. If you want, you can create new issue for auto open completion dialog. Thank you for report.
