### ISSUE TITLE
Color coding and hotlinking in {control} with compound name

### ISSUE THREAD

**Issue by martinbohmcz** [mesour-intellij-plugins/latte-pro-issues#27]
**Describe the bug**
Tag {control} with compound name based on object's property is not correctly highlighted and neither work the hotclick to property / method.

**Environment (please complete the following information):**
 - PhpStorm version [e.g. 2022.2]
 - Plugin version [e.g. 1.0.2]

**To Reproduce**
Use the code below

**Code**
`{control "form-{$item->getOtherItem()->id}"}`
`{control "form-{$item->id}"}`

**Screenshots**
![image](https://user-images.githubusercontent.com/15814845/184120162-fbd2be01-e989-4471-851b-b6ec144073a0.png)

**Comment by mabar** [comment]
Generally problem is with detection of string interpolation , see #16

**Comment by mesour** [comment]
This issue is duplicate for https://github.com/mesour-intellij-plugins/latte-pro-issues/issues/16
