### ISSUE TITLE
{templateType} should override default variables

### ISSUE THREAD

**Issue by mabar** [mesour-intellij-plugins/latte-pro-issues#29]
** Environment:
- PhpStorm version [e.g. 2022.2]
- Plugin version [e.g. 1.0.2]

When `{templateType}` is defined, only variables from given class are passed to template.
Default variables from `Nette\Bridges\ApplicationLatte\TemplateFactory` (defined by plugin) and from XML configuration should be available in template only if `{templateType}` is not defined (or explicitly defines these variables itself or is DefaultTemplate)

These all should be undefined variables:
![image](https://user-images.githubusercontent.com/20974277/184153149-68b245f6-6017-4606-9c32-fa4047c50e76.png)

```latte
{templateType App\ExampleTemplate}

{$basePath}
{$baseUrl}
{$control}
{$flashes}
{$presenter}
{$user}
```

Also overriding defaults should not be a problem (currently $user is always \Nette\Security\User, even when template uses different type)

```php
namespace App;

final class ExampleTemplate
{

	public \stdClass $user;

}
```

**Comment by mabar** [comment]
Plugin currently suggests both variables - default and from templateType. But only default one is used for autocomplete, references etc.

**Comment by mabar** [comment]
One default variable is missing - `Latte\Runtime\Template $this`
`$this` is the only variable which should be always available, not overriden if `{templateType}` is defined

**Comment by mesour** [comment]
Best priority for detecting var type is:

```
1. {vatType}
2. Local definition {var type $foo}
3. Template class
4. XML configuration
5. Plugin defined
```

This is how I edit it.

**Comment by vvoody-** [comment]
Is this change part of 1.1.8? I just run into this issue trying to override type of $user variable. Specificaly {templateType ...} and xml config dont work for me, only {varType ...} macro works.

**Comment by vvoody-** [comment]
I made it working somehow editing of unrelated stuff in xml config file - I assume it refreshes itself on fly. But after IDE restart its broken again. When I type `$us` I see both $user suggestions, but suggested methods on users object `$user->...` are only from `\Nette\Security\User`

edit: It turned out Im on last version of Latte Pro - 1.0.11 released in april so this fix is probably not in it yet
