### ISSUE TITLE
Syntax error in multiline html tag

### ISSUE THREAD

**Issue by mabar** [mesour-intellij-plugins/latte-pro-issues#32]
** Environment:
- PhpStorm version [e.g. 2022.2]
- Plugin version [e.g. 1.0.3]

```html
<br
	class=""
/>
```

![image](https://user-images.githubusercontent.com/20974277/184660031-cad124de-89e7-49f3-ac7b-c60dcc5b7fdf.png)

**Comment by mesour** [comment]
@mabar tags ends with `/>` are not allowed as multiline.

**Comment by mabar** [comment]
But why not? They work perfectly fine in HTML, but Latte reports an error.

**Comment by mesour** [comment]
Because this is edge case and it is hart to implement and here are no benefits from this syntax. This is old XHTML syntax, today it is not necessary use `/>`.

**Comment by mabar** [comment]
Oh, I see :) Just removed `/` and it's okay, thanks
