### ISSUE TITLE
Broken parsing with unpaired tag with missing registration

### ISSUE THREAD

**Issue by SendiMyrkr** [mesour-intellij-plugins/latte-pro-issues#4]
When you use code like this, pluing starts throw meaningless error.

`{block test}
    {if strpos($warehouseState, 'REZERV')}
        {url $something}
    {else}
        b
    {/if}
{/block}`

`{block t`

'#', <php array>, <php class init>, <php function>, <php link>, <php list of variables definition>, '?', '[Latte] T_PHP_DOUBLE_QUOTE_LEFT', '[Latte] T_PHP_FILE_PATH', '[Latte] T_PHP_IDENTIFIER', '[Latte] T_PHP_LEFT_BRACKET', '[Latte] T_PHP_LEFT_NORMAL_BRACE', '[Latte] T_PHP_MACRO_SEPARATOR', '[Latte] T_PHP_MIXED', '[Latte] T_PHP_NAMESPACE_RESOLUTION', '[Latte] T_PHP_NULL', '[Latte] T_PHP_NULL_MARK', '[Latte] T_PHP_NUMBER', '[Latte] T_PHP_OR_INCLUSIVE', '[Latte] T_PHP_SINGLE_QUOTE_LEFT', '[Latte] T_PHP_STRING', '[Latte] T_PHP_TYPE', '[Latte] T_PHP_TYPE_ARRAY' or '[Latte] T_PHP_VARIABLE' expected, got 'test'

`{block test}` => '' unexcpected

When you use code like this than errors are extended to if tag.

`{block test}
    {if strpos($warehouseState, 'REZERV')}
        {url $something}
    {else}
        {url $something}
    {/if}
{/block}`

Look like reason of this is unregistered unpair tag.

**Comment by mesour** [comment]
@SendiMyrkr can you try it with `1.0.2` version of plugin? In my opinion, this is older version.

**Comment by SendiMyrkr** [comment]
You have right, with 1.0.2 it works correctly
