### ISSUE TITLE
Undefined filter should offer Add custom filter

### ISSUE THREAD

**Issue by mabar** [mesour-intellij-plugins/latte-pro-issues#40]
It seems I can't register custom filters the same way as macros

![image](https://user-images.githubusercontent.com/20974277/185037413-ee47ca64-4033-4ea2-b070-1c41279e7091.png)

**Comment by mesour** [comment]
It is not possible, because plugin have only XML configurations for filters. For tags exist preferences in IDE. In project can be many XML files and the plugin does not know which file to write the filter to

**Comment by 3it-jan-cernin** [comment]
Couldn't one of these be achievable?

A) put a scopeless (for the whole project) filters setting into IDE preferences
B) popup a directory selection to choose from, and [ add to | create ] needed xml file
C) allow a button "add custom filter" in latte-pro IDE preferences where I can define name and arguments to get xml string generated so I can put it anywhere

Anything but "google docs and write a xml" would be neat imo. Saying "it's not possible", if you have full controll, should not stop a programmer :).

**Comment by mabar** [comment]
@3it-jan-cernin Plugin developers are limited by API offered by JetBrains. Some things that are told to be not possible may be possible, but it is sometimes really hard to get all the necessary informations.

It's not really that complicated to write XML config and all developers using given package can benefit from it with no additional work.
