### ISSUE TITLE
Detection of unknown tags is not always working

### ISSUE THREAD

**Issue by mabar** [mesour-intellij-plugins/latte-pro-issues#41]
**Environment:**
 - PhpStorm version [e.g. 2022.2]
 - Plugin version [e.g. 1.0.4]

All of following tags are unknown. Currently:

- Only `foo` is reported unknown
- `baz` is reported as unknown only *sometimes*. Each time I add blank line under tag usage and save file, it *may* change.
- Detected unknown tags are offered to be added as unpaired. I suggest to also offer to add them as pair (if it is not possible to offer right one based on usage)

```latte
{foo}{/foo}

{bar/}

{baz a}
```

![image](https://user-images.githubusercontent.com/20974277/185037928-53def836-164b-4245-9973-3d0fca0f8465.png)

**Comment by mesour** [comment]
@mabar you have syntax error `{foo}{/foo}`. If you have syntax error, IDE will stop parsing after that element.

Here was another error in detecting unknown tag closing with `/}`, it will be fixed in `1.0.5`.

**Comment by mabar** [comment]
I don't understand, how is that an error? Empty pair tag is invalid?

**Comment by mesour** [comment]
@mabar unknown pair tag is invalid for parser, you can open new issue for this. It's a different problem than problem in this issue.
