### ISSUE TITLE
Project indexing hungs

### ISSUE THREAD

**Issue by myrek007** [mesour-intellij-plugins/latte-pro-issues#44]
**Describe the bug**
Project indexing hungs when plugin enabled.

**Environment (please complete the following information):**
 - PhpStorm 2022.2
 - Plugin version 1.0.4

**Comment by mesour** [comment]
@myrek007 I need more information. Which file doing this? Is some error in this file (if not, can you send here content of this file)?

**Comment by mabar** [comment]
@myrek007 Click on the indexing progress bar, it should show the current file being indexed. File is probably too long or have some special syntax.
That file is gonna be needed for issue replication. Try to replicate issue with that file in standalone repo and send minimal code which reproduces the issue

**Comment by myrek007** [comment]
Everytime I restart IDE it hungs at different file. I don't think it's reproducible this way.

**Comment by mabar** [comment]
Could you move one or more of these files to own project and check if the issue will appear?
It is really hard to tell what is happening withou having code to reproduce it.

**Comment by myrek007** [comment]
I may offer you a remote access to my desktop to see it yourself.

**Comment by mesour** [comment]
@myrek007 it can be in more files. PhpStorm not indexing files in same order. It is not necessary, you can record it and upload video to youtube or can you post here one of these files?

**Comment by myrek007** [comment]
[sample.zip](https://github.com/mesour-intellij-plugins/latte-pro-issues/files/9363148/sample.zip)

**Comment by mabar** [comment]
@myrek007 Change `{label contact_email}` etc. to `{label contact_email/}` and you should be fine.
It is required from Latte 3 to have unpair {label} written that way.

@mesour It completele freezes phpstorm even with one file.

**Comment by myrek007** [comment]
Will try.
Does it explain why it hungs on SVG, TSX or JAR as well?

**Comment by myrek007** [comment]
OK, it worked, project is now indexed.
Are you going to fix the issue? I cannot prevent such typos in all projects.

**Comment by mabar** [comment]
On JAR?

Hmm, maybe same issue as in original plugin, @mesour? https://github.com/nette-intellij/intellij-latte/issues/186

**Comment by myrek007** [comment]
> On JAR?

Fixing the "label" pairing issue in latte files resulted that indexing does not hung anymore. Not even on JAR, TSX, SVG etc.
Weird.

**Comment by mabar** [comment]
I guess it's caused by multithreading. PHPStorm indexed multiple files at once and when Latte indexing got stuck it showed one of the currently indexed files.

**Comment by mesour** [comment]
@myrek007 please try it in `1.0.7`
