### ISSUE TITLE
Supress plugin defined variables if exists in template

### ISSUE THREAD

**Issue by SendiMyrkr** [mesour-intellij-plugins/latte-pro-issues#48]
I think should be great if plugin will ignore degined global variables in XML if there is some in presenter/control templates. I believe that order should be local {varType ...} -> Template class -> XML defined, now it's probably like {varType ...} ->XML -> Template class

eg.
```

class PresenterTemplate {
    /** @var array<FlashMessage> */
    public array $flashes;
}

{templateType PresenterTemplate}

{foreach $flashes as $msg}
     {$msg->...} {* suggest by variable defined in NetteAplication.xml, but i think PresenterTemplate should be prefered *}
{/foreach}
```

**Comment by mabar** [comment]
Imho covered by #29

**Comment by SendiMyrkr** [comment]
oh, sure. you have right. So i guess it's a duplicate and can be closed.
