### ISSUE TITLE
Code marked as error within 'n:syntax="off"' block

### ISSUE THREAD

**Issue by martinbohmcz** [mesour-intellij-plugins/latte-pro-issues#50]
**Describe the bug**
I do not know if this is a bug, or feature request, but I've got my code underlined with "unknown tag" error even though it was within a 'n:syntax="off"' block.

**Environment (please complete the following information):**
 - PhpStorm version [e.g. 2022.2.1]
 - Plugin version [e.g. 1.0.5]

**To Reproduce**
1. Enter the code below into empty template

**Code**
```
	<script n:syntax="off">
		$(document).ready(function () {
			$('#zalozky').tabs({tabElement: "h2"});
		});
	</script>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/15814845/186099691-6f2717b4-df08-4d1d-bac5-e3846ed6dffc.png)

**Comment by mesour** [comment]
@martinbohmcz As workaround use `{ tabElement: "h2" }` with spaces. This problem is not possible to fix now. I have tried it in the past and there are problems.

**Comment by martinbohmcz** [comment]
OK. I will use the workaround you mentioned.

**Comment by mesour** [comment]
Possible solution in v1.1.0 is use tag `{syntax off}` - #122.

`n:syntax="off"` is probably possible to implement (for specific html tags eg: script, style), but it will be in any future version.
