### ISSUE TITLE
Reformat code does not align correctly after comment

### ISSUE THREAD

**Issue by martinbohmcz** [mesour-intellij-plugins/latte-pro-issues#53]
**Describe the bug**
When I have code below (entered e.g. by pasting) and try to reformat it by CTRL+ALT+L, the HTML gets formated, but {control…} tag does not. It occurs only if the comment {*…*} is present.

**Environment (please complete the following information):**
- PhpStorm version [e.g. 2022.2.1]
- Plugin version [e.g. 1.0.5]

**To Reproduce**
Steps to reproduce the behavior (or attach video):
1, Enter code below
2. Run "Reformat code" (CTRL+ALT+L)

**Code**
```
<div>
	<div>
		{*
		…
		*}
{control someForm}
	</div>
</div>

```

**Additional context**
Issue might be related to #49

**Comment by mesour** [comment]
@martinbohmcz i moved this content to https://github.com/mesour-intellij-plugins/latte-pro-issues/issues/49
