### ISSUE TITLE
Inspect code... throws StackOverflowError

### ISSUE THREAD

**Issue by mabar** [mesour-intellij-plugins/latte-pro-issues#55]
Running *Inspect code...* on Latte files in https://github.com/orisai/cmf throws following exception. Specifically it always reports on this file https://github.com/orisai/cmf/blob/707e02423e68a74302eb0fd0aea28939a5a1c451/src/UI/Form/Latte/FormInputs.latte

** Environment:
- PhpStorm version [2022.2]
- Plugin version [1.0.5]

[exception.txt](https://github.com/mesour-intellij-plugins/latte-pro-issues/files/9440602/exception.txt)

**Comment by mesour** [comment]
@mabar it was because `{do $parent = $parent->getFoo()}`. I don't know, how to resolve this issue now, but at least I modify it for now so that the exception does not throw. I will create new issue as enhancement for this case.

**Comment by mabar** [comment]
It works now, thanks
