### ISSUE TITLE
Unknown tag {vartype}, did you mean {varType}

### ISSUE THREAD

**Issue by martinbohmcz** [mesour-intellij-plugins/latte-pro-issues#59]
**Describe the bug**
Tags in Latte are obviously case-sensitive. (mentioned here: https://forum.nette.org/cs/33960-latte-pojmenovani-znacek-a-velka-pismena). Plugin should warn about that.

**Environment (please complete the following information):**
 - PhpStorm version [e.g. 2022.2.1]
 - Plugin version [e.g. 1.0.6]

**Code**
`{vartype Class $foo}` (notice the lowercase "T")

**Additional context**
When executed, you get Tracy error 'Unknown tag {vartype}, did you mean {varType}'

**Comment by mesour** [comment]
@martinbohmcz please try it in `1.0.7`

**Comment by martinbohmcz** [comment]
@mesour: It gets underlined now with "Unknown tag" warning. Cool. :) Thank you.

I dare to push this a bit further. It would be much nicer if the plugin suggests that the "T" should be uppercase. It could apply for other tags too. Is something like that possible?

**Comment by mesour** [comment]
@martinbohmcz yes, suggestion is possible. But it is for another issue. Can you open new issue with this as enhancement?
