### ISSUE TITLE
Mark non-class in {VarType}

### ISSUE THREAD

**Issue by martinbohmcz** [mesour-intellij-plugins/latte-pro-issues#62]
**Is your feature request related to a problem? Please describe.**
I have `{varType path\to\somewhere $variable}` in my template. But the Type `path\to\somewhere` by mistake leads to a non-class (in my case to a namespace).

**Describe the solution you'd like**
I would like that the plugin notify/warn me about this.

**Comment by mabar** [comment]
Only namespace should be reported (and probably resource and trait for consistence with php?), other non-class types are fine
Also solution should take into account namespace and class can have same name (see code bellow)

```php
namespace Foo {
    class Bar {}
}

namespace Foo\Bar {
    class Baz{}
}

namespace {
    var_dump(new \Foo\Bar());
}
```

**Comment by mesour** [comment]
Try it in 1.1.1

**Comment by martinbohmcz** [comment]
It works, thank you.
