### ISSUE TITLE
Lost type of variable

### ISSUE THREAD

**Issue by lulco** [mesour-intellij-plugins/latte-pro-issues#64]
Plugin lost type of variable when it is used in function:

```
{varType FooBar[] $fooBars}

{foreach $fooBars as $fooBar}
    {$fooBar->doSomething()} // everything ok
{/foreach}

{foreach array_slice($fooBars, 0, 4) as $fooBar}
    {$fooBar->doSomething()} // lost type of $fooBar (should be FooBar)
{/foreach}
```

There are several functions like this, maybe plugin can get inspiration in [phpstan](https://github.com/phpstan/phpstan-src/tree/1.9.x/src/Type/Php)

**Comment by mesour** [comment]
@lulco duplicity https://github.com/mesour-intellij-plugins/latte-pro-issues/issues/131
