### ISSUE TITLE
Undefined property called non-statically is reported as static

### ISSUE THREAD

**Issue by mabar** [mesour-intellij-plugins/latte-pro-issues#7]
** Environment:
- PhpStorm version [e.g. 2022.2]
- Plugin version [e.g. 1.0.1]

Yeah, minor issue, just feels weird.

![image](https://user-images.githubusercontent.com/20974277/183978526-86db96c0-721f-4afe-8420-a63012fdb5f7.png)

**Comment by lulco** [comment]
Same with non-static method calls reported as static
<img width="542" alt="Screenshot 2022-08-10 at 23 01 45" src="https://user-images.githubusercontent.com/9377319/184019352-4ab77026-9725-4cc4-ae69-c37d658047ca.png">
