### ISSUE TITLE
Attribute autocomplete for tags from intellij-latte-pro.xml

### ISSUE THREAD

**Issue by forstjiri** [mesour-intellij-plugins/latte-pro-issues#75]
**Is your feature request related to a problem? Please describe.**
Attributes can be deffined with their types in XML but no autocomplete or checking is done in template.

**Describe the solution you'd like**
Same autocomplete as is available in php with named attributes.

**Describe alternatives you've considered**
There is no alternative except searching for other occurences or into .xml.

**Additional context**
Our company will heavilly rely on tags (macros) to inject components HTML

**Current state**
![where it should work](https://user-images.githubusercontent.com/6242394/196681300-f3c850d5-e20a-4091-b375-1afb63145c67.png)

**How it should work**
![How it works in PHP](https://user-images.githubusercontent.com/6242394/196683711-1a3b5b47-88fa-4e76-9444-31afa2f2fee2.png)

**Comment by mesour** [comment]
@aiphee this is not how tag arguments will work. It only allows you define which content and PHP type can be in tag for validation inspection. It win not work as completion for named arguments or array keys.
