### ISSUE TITLE
Plugin has crashing with wierd invalid inputs

### ISSUE THREAD

**Issue by SendiMyrkr** [mesour-intellij-plugins/latte-pro-issues#76]
PHPStrom: 2022.2.3
Plugin: 1.0.8

Sometimes when I wildly edit templates that get into a weird invalid state because of this, the plugin absolutely kills my PHPStrom. The only solution is to kill the process. In this case, the template is not saved or an error message pops up so it is not obvious why this happened and on what input.

There is a possible realtion to issue #68

**Comment by mesour** [comment]
It this still happening in 1.0.11?

**Comment by SendiMyrkr** [comment]
looks ok now
