### ISSUE TITLE
No Tailwind CSS autocomplete

### ISSUE THREAD

**Issue by MartinLojda** [mesour-intellij-plugins/latte-pro-issues#77]
I don't know if it is really related to this plugin, but it would be nice to solve the issue.

More info can be found here:
https://youtrack.jetbrains.com/issue/WEB-55325/Tailwind-CSS-autocomplete-for-Latte-templates

Thank you for looking into this!

**Comment by janmotycka13** [comment]
@mesour How is this problem going please?

**Comment by mabar** [comment]
Tailwind plugin seems to be mostly broken and missing extension points that could a plugin providing an officially not supported file format use. Probably nothing can be done on Latte plugin side at this moment

**Comment by Creeperface01** [comment]
@mabar apparently it's working in twig files for instance. So there's probably something that can be done on Latte plugin side.

**Comment by mabar** [comment]
@Creeperface01 Thanks for reminder. Recently someone posted hint that it could be done in config file for Tailwind. Could you try it?

If it works, we could investigate if it can be added for all users on either Latte or Tailwind side. Really depends just on whether Tailwind plugin provides API for other plugins or just supports Twig by default.

```
"includeLanguages": {
    "latte": "html"
  }
```

![image](https://github.com/mesour-intellij-plugins/latte-pro-issues/assets/20974277/eb085b1a-b503-443f-bb5f-48b485fcc341)

**Comment by Creeperface01** [comment]
> @Creeperface01 Thanks for reminder. Recently someone posted hint that it could be done in config file for Tailwind. Could you try it?
> 
> If it works, we could investigate if it can be added for all users on either Latte or Tailwind side. Really depends just on whether Tailwind plugin provides API for other plugins or just supports Twig by default.
> 
> ```
> "includeLanguages": {
>     "latte": "html"
>   }
> ```
> 
> ![image](https://user-images.githubusercontent.com/20974277/252625176-eb085b1a-b503-443f-bb5f-48b485fcc341.png)

This does not seem to be working. At least for me nothing changes

**Comment by mabar** [comment]
Seems to be working for me. (tailwind.css is file which contains `@tailwind base;` etc. definitions in my case)

Make sure to save the file and restart phpstorm. Also, do you have latest IDE and plugin version? There were some bugs related to older Tailwind plugin and IDE versions.

![image](https://github.com/mesour-intellij-plugins/latte-pro-issues/assets/20974277/1da4701b-5b4d-4ba9-901c-1526719eb96a)
