### ISSUE TITLE
Error updating after DocumentEventImpl

### ISSUE THREAD

**Issue by SendiMyrkr** [mesour-intellij-plugins/latte-pro-issues#80]
[content.txt](https://github.com/mesour-intellij-plugins/latte-pro-issues/files/10366883/content.txt)
[induced.txt](https://github.com/mesour-intellij-plugins/latte-pro-issues/files/10366884/induced.txt)
[stacktrace.txt](https://github.com/mesour-intellij-plugins/latte-pro-issues/files/10366885/stacktrace.txt)

**Comment by mesour** [comment]
Is it still persist in 1.0.12? If yes, please reopen issue or create new one
