### ISSUE TITLE
Cannot invoke "com.intellij.lang.ASTNode.getTreeNext()" because "last" is null

### ISSUE THREAD

**Issue by SendiMyrkr** [mesour-intellij-plugins/latte-pro-issues#81]
[induced.txt](https://github.com/mesour-intellij-plugins/latte-pro-issues/files/10366890/induced.txt)
[stacktrace.txt](https://github.com/mesour-intellij-plugins/latte-pro-issues/files/10366891/stacktrace.txt)

**Comment by mesour** [comment]
If it is still persist in 1.0.12, please reopen issue or create new one
