### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by delacry** [mesour-intellij-plugins/latte-pro-issues#86]
**Describe the bug**
PhpStorms logs the exception.

**Environment (please complete the following information):**
 - PhpStorm version 2022.3
 - Plugin version 1.0.10

It occurs when I randomly click on some doctrine entity or probably file that is used somewhere in some template.

There are multiple errors:
https://code.rixafy.pro/alkGjz54
https://code.rixafy.pro/6w5MXWxB
https://code.rixafy.pro/Byx70Z5E

**Comment by mesour** [comment]
@Rixafy Is this still persist in 1.0.12? If yes, please reopen issue.
