### ISSUE TITLE
Plugin doesn't work with EAP 2023.1

### ISSUE THREAD

**Issue by Lumeriol** [mesour-intellij-plugins/latte-pro-issues#87]
**Describe the bug**
the plugin is marked as incompatible with the new 2023.1 EAP. Can you add support for it?

**Environment (please complete the following information):**
 - PhpStorm version [2023.1]
 - Plugin version [all]

**Comment by mesour** [comment]
@Lumeriol Im not fixing plugin for EAP version. Because EAP version are not complete/fixed and can be changed before release.
