### ISSUE TITLE
Unused variable indication is missing - more than one variable declarations in one {var} tag

### ISSUE THREAD

**Issue by mildabre** [mesour-intellij-plugins/latte-pro-issues#90]
Hi, I have found this bug in latte tag {var} - if you declare more than one variable in one {var} tag, separated by comma, second and following declarations have missing "unused variable indication" with grey color.

Unused variable indication is a very handy so pls fix this bug.

![latte-pro-plugin-missing-unused-variable-indication-var](https://user-images.githubusercontent.com/34324008/220808576-2608c819-24e2-43f0-84e7-2f1c21ab33dd.png)

Thanks

**Comment by mesour** [comment]
Dev info: Probably related with #89
