### ISSUE TITLE
Bug - missing opening tag stop plugin function

### ISSUE THREAD

**Issue by mildabre** [mesour-intellij-plugins/latte-pro-issues#93]
Hi,
I found complicated bug which in result stop plugin function (underlining errors and completing variable names). The bug is connected with closing latte tag without opening one. The same result makes complete pair of unknown tag.

See screenshots of samples:

a) unpaired unknown tags makes no problems - red underlining works and everything else works:

![latte-tags-01](https://user-images.githubusercontent.com/34324008/221052785-a7046d92-fb38-4d84-be5d-c86d459f031c.png)

b) unclosed closing tag (unpaired) - missing red underlining of wrong tag {/if} but false red underlining of closing tag of block with false message "unknown close tag", from this point plugin stop function:

![latte-tags-02](https://user-images.githubusercontent.com/34324008/221052931-25c1237a-14fe-4bdb-a4d8-f0755a122730.png)

c) unclosed unknown closing tag (unpaired) makes the same troubles as above:

![latte-tags-03](https://user-images.githubusercontent.com/34324008/221053008-09f7534e-3ef1-4cf6-97bd-445724c9a2ae.png)

d) two unclosed closing tags (unpaired) - missing red underlining of first unclosed tag {/if}, red underlining of second wrong tag, from this point plugin stop function:

![latte-tags-04](https://user-images.githubusercontent.com/34324008/221053049-a9d2d610-306d-4570-bcec-b4d7740f5dd0.png)

e) two unclosed unknown closing tags (unpaired) makes the same troubles as above:

![latte-tags-05](https://user-images.githubusercontent.com/34324008/221053090-d7fd9c84-3a5a-4c5c-b888-81ff351c8bed.png)

f) pair of unknown tag has the same result as unclosed closing tag:

![latte-tags-06](https://user-images.githubusercontent.com/34324008/221053160-3ffe4464-cce5-4674-98cf-d88347087536.png)

g) two pairs of unknown tag has the same result as two unclosed closing tags:

![latte-tags-07](https://user-images.githubusercontent.com/34324008/221053257-ec43bca7-a7b6-4005-b1a6-63c7f4e5f035.png)

It is not an academical problem, in case you have two unknown tags somewhere in template (for example {translate}...{/translate}), from the point of the second one the plugin works not !!!

**Comment by mabar** [comment]
Probably same problem as with pair {label foo} without closing tag
See #69

**Comment by mesour** [comment]
Done in 1.0.11
