### ISSUE TITLE
Custom tag configuration  in intellij-latte-pro.xml works NOT!

### ISSUE THREAD

**Issue by mildabre** [mesour-intellij-plugins/latte-pro-issues#94]
Hi,

I have configured custom tag {translate}{/translate} and template variable $appDir in intellij-latte-pro.xml as defined in documentation:

https://mesour-intellij-plugins.github.io/latte.html#xml-config

code:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE latte PUBLIC "-//LATTE//Latte plugin XML V0.0.1//EN" ".idea/intellij-latte-pro/xmlSources/Latte.dtd">
<latte vendor="brecher/latte-plugin" version="1">
    <tags>
        <tag name="translate" type="PAIR" />
    </tags>
    <variables>
        <variable name="appDir" type="string" />
    </variables>
</latte>
```

Configuration of the variable $appDir was successful, but configuration of custom tag {translate} NOT - bug no. 1.

Phpstorm shows one error in the file intellij-latte-pro.xml - see screenshot:

![xml-latte-pro](https://user-images.githubusercontent.com/34324008/221066060-e53ee537-1a87-40db-81d3-1e36f3d123c6.png)

This is probably bug no. 2 - because the xml file makes the configuration, there is no need to support xml configuration with another configuration in phpStorm setting !

To solve this problem I have used standby workaround and used the automatically created xml configuration file /.idea/latte-pro.xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="LatteSettings">
    <option name="a">
      <list>
		<LatteTagSettings name="translate" type="PAIR" />
      </list>
    </option>
  </component>
</project>
```

This solution works, but in the documentation is recommended the standard solution intellij-latte-pro.xml, and in future may happen will be not supported.

Therefore pls fix the above described bugs.

Thanks

**Comment by mabar** [comment]
Documentation never told you to touch internal (/.idea) files.
https://forum.nette.org/cs/35778-plugin-latte-pro-chyba-pridani-custom-paired-tag-jak-vyresit-rucne#p222935
